### ISSUE TITLE
Theme flags update for 1.5.1, but no package available

### ISSUE THREAD

**Issue by BigActual** [disAbility-Connections/ion-ap3-child#11]
Message "Ion AP3 1.5.1 is available. Check out what's new or update now." is flying at the top of the admin dashboard, but when the update is attempted, there's no package available. Would you please manually pull it down and push the change when you are able, this week?

**Comment by d4mation** [comment]
Updated. Seems the License Key was not entered. It will now update properly from the dashboard.
