### ISSUE TITLE
Be able to Click on the Category within the listing like “gas station” “Discount Store” “Bar” and see others that have been surveyed.

### ISSUE THREAD

**Issue by BigActual** [disAbility-Connections/ion-ap3-child#2]
Be able to Click on the Category within the listing like “gas station” “Discount Store” “Bar” and see others that have been surveyed.  ** see search bar info in number 9 in my email, issue #1 here in GitHub, this might fix this question also.

**Comment by d4mation** [comment]
This one may be a bit challenging, since the links within the individual Posts are taken directly from the WP site. I'd need to find a way to filter those returned results to provide URLs that are compatible with the App.

**Comment by BigActual** [comment]
So, the category in the facility single is a hyperlink in the site already, so AppPresser should be able to use those without issue? or are saying that only certain types of links can be pulled through?

**Comment by d4mation** [comment]
It will have to stay a Hyperlink. 

> A final question would be, is it possible to link to the List page with custom parameters without creating a Custom Page in the app? The Client wants links from within the Post Content for other Categories to work within the App and I was thinking to run a Filter on the Post Content to catch those and convert them into something that the App can parse, but I am not sure if that is possible without having a Custom Page that already exists for that Category. I am not sure if a generic page could be made to handle these requests or if another solution would be possible.

> Only thing I can think that might come close to that would be using the WordPress Post Lists. **You would not be able to inject an angular derived post list without the custom page being built as you suggested.**

Emphasis mine. This means that we could use the WordPress Posts List feature if we really wanted, but it wouldn't look anything like the rest of the App when they clicked that link. 

Viewing the documentation for that here: https://docs.apppresser.com/article/339-wordpress-post-lists

> It does not use the WP-API, it is an iframe view of your site

So it would just use an iFrame to view their website from within the App. May as well leave them regular links and have it open the web browser at that point :/

**Comment by BigActual** [comment]
> This means that we could use the WordPress Posts List feature if we really wanted, but it wouldn't look anything like the rest of the App when they clicked that link.
Well, with proper styling the post list could look like the app. Those pages could be made only intentionally available to the app and styled with their CSS in the websites theme. 
I like this solution. I'll pm you offline to discuss the details.
> May as well leave them regular links and have it open the web browser at that point :/
That's not the intent, and it would break the UX for the end user. What happens in the app stays in the app. For marketing purposes and relationship building purposes.  We want people to come back in here and reuse these services. Not bookmark pages in web browsers.

**Comment by d4mation** [comment]
> Well, with proper styling the post list could look like the app. Those pages could be made only intentionally available to the app and styled with their CSS in the websites theme.

I think you misunderstood here. The Posts are the same Posts that you normally see when you search inside of the app. However, now you're viewing the website within an iFrame. This means that they're viewing the full website which does not have the same styling as the search results inside of the app.

> it would break the UX for the end user

It already does break the UX for the end user if we implement it with an iFrame. You're now using a website inside of an iFrame inside another app, which is always super clunky.

**Comment by BigActual** [comment]
Changing to no-fix. With the addition of Relevansi as the search toolset on the website, searching for pizza or restaurant or whatever has been significantly improved. This should be a non-issue. Closing and keeping for documentation and future reference.
