### ISSUE TITLE
Declutterify the layout

### ISSUE THREAD

**Issue by BigActual** [disAbility-Connections/ion-ap3-child#4]
Find a way to display information in a less cluttered way.  Colors, segments, shapes to break apart and separate questions and their answers.**When you are on the page that lists the establishment's name and survey information it is very difficult to read.  Is there a way to reformat this?

**Comment by d4mation** [comment]
Hmm, this may take some creative styling. As mentioned is other issues, this is data directly returned from the WP site. This also includes the HTML that it uses for the little collapsable elements, but those won't be able to be directly used. It _may_ be possible to write some crazy RegEx to convert this into an Ionic element of some kind, but adding some styling for a Table would likely be just as usable and much simpler to accomplish while being less likely to break.

**Comment by BigActual** [comment]
You are able to style the table in the AppPresser end of things?

**Comment by d4mation** [comment]
You can include arbitrary CSS. It is just a bit of a pain to do so since it only accepts Vanilla CSS. 

I may end up making another Repo in order to just compile SCSS for the App.

**Comment by BigActual** [comment]
Bold each section (Entrance Accessibility, Seating, etc.)
and indent the second line of the ordered list.

**Comment by d4mation** [comment]
![image](https://user-images.githubusercontent.com/7770631/51255714-c47c7380-1971-11e9-9e46-f6b2c5f27dcc.png)
