### ISSUE TITLE
Bring up listings by proximity or list in alphabetical order when displaying

### ISSUE THREAD

**Issue by BigActual** [disAbility-Connections/ion-ap3-child#6]
Currently, the listings that come up when you choose the county are in no kind of order (I believe you said you thought they were ordered by date entered)  is there a way to do this alphabetically?  Or in some other order from?

**Comment by d4mation** [comment]
Alphabetical would be the most realistic here, since currently the Posts do not have GPS coordinates associated with them (And AppPresser would also have to access Location Data to make that work, which I am not sure if it can, as well as pass that data into the query)

**Comment by BigActual** [comment]
Please proceed with this.

**Comment by BigActual** [comment]
What is the status on this Eric? I thought I was all set, but I'm unable to explain this to the client.
