### ISSUE TITLE
Purple search bar in iPhone difficult to see

### ISSUE THREAD

**Issue by BigActual** [disAbility-Connections/ion-ap3-child#8]
Brian has an android phone and I have an iPhone.  I think he said that his search bar is white but mine is purple and very difficult to see.

**Comment by d4mation** [comment]
Are there screenshots of this in action? I'm not sure why the Search Bar would be a different color on iOS unless it were a bug/oversight in AppPresser. But we should be able to correct this with CSS if needed.

**Comment by d4mation** [comment]
iOS: 

![image](https://user-images.githubusercontent.com/7770631/50990975-8c90ae80-14e1-11e9-8d6a-df3665a6bf8b.png)

Android: 

![image](https://user-images.githubusercontent.com/7770631/50990992-99150700-14e1-11e9-9cee-68cf6c9ecce7.png)

**Comment by d4mation** [comment]
I pushed a potential fix for this, but I do not have an iOS device with which to check in easily. 

There is CSS there to have the Search Box have a white background, but I think iOS/Safari is ignoring it. So I made the background color of its container white too. You cannot see that I've done that on any other device, but it hopefully corrects the issue with iOS.

**Comment by BigActual** [comment]
I've asked the client to test on her iphone.

**Comment by BigActual** [comment]
Verified correct by client.
